"use client";

import { TranscriptPreview } from "@/components/transcript-preview";
import { captionLanguageLabel } from "@/lib/speakers";
import type { ConvertError, ConvertSuccess } from "@/lib/types";
import { useMemo, useState, type FormEvent } from "react";

type Status = "idle" | "loading" | "ready" | "error";

function downloadMarkdown(filename: string, markdown: string) {
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const href = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = href;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(href);
}

export function Converter() {
  const [url, setUrl] = useState("");
  const [status, setStatus] = useState<Status>("idle");
  const [result, setResult] = useState<ConvertSuccess | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const canSubmit = url.trim().length > 0 && status !== "loading";

  function onClear() {
    setUrl("");
    setError(null);
    setResult(null);
    setCopied(false);
    setStatus("idle");
  }

  const meta = useMemo(() => {
    if (!result) return [];
    return [
      result.channel ? `Channel ${result.channel}` : null,
      `${result.segmentCount} turns`,
      captionLanguageLabel(result.languageName, result.isAutoGenerated),
    ].filter(Boolean) as string[];
  }, [result]);

  async function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setStatus("loading");
    setError(null);
    setCopied(false);
    setResult(null);

    try {
      const response = await fetch("/api/convert", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url }),
      });
      const data = (await response.json()) as ConvertSuccess | ConvertError;
      if (!response.ok || "error" in data) {
        const message =
          "message" in data
            ? data.message
            : "Conversion failed. Try a public video that has captions.";
        setError(message);
        setStatus("error");
        return;
      }
      setResult(data);
      setStatus("ready");
    } catch {
      setError("Network error. Make sure the app is still running.");
      setStatus("error");
    }
  }

  async function onCopy() {
    if (!result) return;
    try {
      await navigator.clipboard.writeText(result.markdown);
    } catch {
      const textarea = document.createElement("textarea");
      textarea.value = result.markdown;
      textarea.setAttribute("readonly", "true");
      textarea.style.position = "fixed";
      textarea.style.left = "-9999px";
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      textarea.remove();
    }
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1600);
  }

  return (
    <div className="mx-auto flex w-full max-w-5xl flex-col gap-8">
      <form onSubmit={onSubmit} className="flex flex-col gap-3">
        <label htmlFor="youtube-url" className="text-sm tracking-[0.18em] text-[#c45c3e]">
          YOUTUBE LINK
        </label>
        <div className="flex flex-col gap-3 sm:flex-row">
          <div className="relative flex-1">
            <input
              id="youtube-url"
              value={url}
              onChange={(event) => setUrl(event.target.value)}
              placeholder="https://www.youtube.com/watch?v=…"
              autoComplete="off"
              spellCheck={false}
              className="min-h-14 w-full rounded-sm border border-[#d8cebf] bg-[#fffdf8] px-4 pr-12 text-base text-[#1c1915] outline-none ring-[#c45c3e]/30 placeholder:text-[#b3a899] focus:ring-2"
            />
            {url ? (
              <button
                type="button"
                onClick={onClear}
                aria-label="Clear link"
                className="absolute top-1/2 right-2 flex h-9 min-w-9 -translate-y-1/2 items-center justify-center rounded-sm px-2 text-sm text-[#7a7166] hover:bg-[#efe6d6] hover:text-[#1c1915]"
              >
                Clear
              </button>
            ) : null}
          </div>
          <button
            type="submit"
            disabled={!canSubmit}
            className="min-h-14 rounded-sm bg-[#c45c3e] px-6 text-sm font-medium tracking-wide text-[#fff7f0] transition enabled:hover:bg-[#b04d31] disabled:cursor-not-allowed disabled:opacity-50"
          >
            {status === "loading" ? "Fetching captions…" : "Convert to Markdown"}
          </button>
        </div>
        <p className="text-sm text-[#7a7166]">
          Existing captions only. Videos without CC cannot be converted.
        </p>
      </form>

      {status === "error" && error ? (
        <div
          role="alert"
          className="rounded-sm border border-[#e3b6a6] bg-[#fff4ee] px-4 py-3 text-sm text-[#8a3d2a]"
        >
          {error}
        </div>
      ) : null}

      {status === "loading" ? (
        <div className="overflow-hidden rounded-sm border border-[#e4d9c8] bg-[#fbf6ec]">
          <div className="h-12 animate-pulse bg-[#efe6d6]" />
          <div className="space-y-3 p-6">
            <div className="h-4 w-2/3 animate-pulse bg-[#efe6d6]" />
            <div className="h-4 w-full animate-pulse bg-[#efe6d6]" />
            <div className="h-4 w-5/6 animate-pulse bg-[#efe6d6]" />
            <div className="h-4 w-3/4 animate-pulse bg-[#efe6d6]" />
          </div>
        </div>
      ) : null}

      {result && status === "ready" ? (
        <section className="overflow-hidden rounded-sm border border-[#e4d9c8] bg-[#fbf6ec] shadow-[0_24px_60px_rgba(48,32,16,0.08)]">
          <header className="flex flex-col gap-4 border-b border-[#eadfcf] px-5 py-4 sm:flex-row sm:items-center sm:justify-between">
            <div className="flex min-w-0 flex-1 items-center gap-4">
              <a
                href={`https://www.youtube.com/watch?v=${result.videoId}`}
                target="_blank"
                rel="noreferrer"
                className="shrink-0 overflow-hidden rounded-sm border border-[#eadfcf] bg-[#efe6d6]"
                aria-label={`Open ${result.title} on YouTube`}
              >
                <img
                  src={`https://i.ytimg.com/vi/${result.videoId}/mqdefault.jpg`}
                  alt=""
                  width={320}
                  height={180}
                  className="h-[72px] w-[128px] object-cover sm:h-[90px] sm:w-[160px]"
                />
              </a>
              <div className="min-w-0">
                <h2 className="truncate font-serif text-xl text-[#1c1915]">
                  {result.title}
                </h2>
                <p className="mt-1 text-sm text-[#7a7166]">{meta.join(" · ")}</p>
              </div>
            </div>
            <div className="flex shrink-0 gap-2">
              <button
                type="button"
                onClick={onCopy}
                className="rounded-sm border border-[#d8cebf] bg-white px-3 py-2 text-sm text-[#1c1915] hover:border-[#c45c3e]"
              >
                {copied ? "Copied" : "Copy"}
              </button>
              <button
                type="button"
                onClick={() => downloadMarkdown(result.filename, result.markdown)}
                className="rounded-sm bg-[#1c1915] px-3 py-2 text-sm text-[#fbf6ec] hover:bg-black"
              >
                Download .md
              </button>
            </div>
          </header>
          <TranscriptPreview videoId={result.videoId} turns={result.turns} />
        </section>
      ) : null}
    </div>
  );
}
