import { captionLanguageLabel, groupSpeakerTurns } from "./speakers";
import type { ConvertSuccess, TranscriptSegment } from "./types";
import { canonicalWatchUrl } from "./youtube-url";

export function formatTimestamp(startMs: number): string {
  const totalSeconds = Math.max(0, Math.floor(startMs / 1000));
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;
  if (hours > 0) {
    return `${hours}:${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}`;
  }
  return `${minutes}:${String(seconds).padStart(2, "0")}`;
}

export function formatDuration(durationSeconds: number | null): string | null {
  if (durationSeconds == null || !Number.isFinite(durationSeconds)) return null;
  return formatTimestamp(durationSeconds * 1000);
}

export function toSafeFilename(title: string): string {
  const cleaned = title
    .replace(/[<>:"/\\|?*\u0000-\u001f]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 80);
  return `${cleaned || "transcript"}.md`;
}

export function buildMarkdown(input: {
  videoId: string;
  title: string;
  channel: string | null;
  durationSeconds: number | null;
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  segments: TranscriptSegment[];
}): string {
  const url = canonicalWatchUrl(input.videoId);
  const duration = formatDuration(input.durationSeconds);
  const languageLabel = captionLanguageLabel(
    input.languageName,
    input.isAutoGenerated,
  );
  const turns = groupSpeakerTurns(input.segments);

  const lines: string[] = [
    `# ${input.title}`,
    "",
    `- Video: [${url}](${url})`,
  ];

  if (input.channel) {
    lines.push(`- Channel: ${input.channel}`);
  }
  if (duration) {
    lines.push(`- Duration: ${duration}`);
  }
  lines.push(`- Caption language: ${languageLabel}`);
  lines.push("");
  lines.push("## Transcript");
  lines.push("");

  for (const turn of turns) {
    lines.push(`[${formatTimestamp(turn.startMs)}] ${turn.text}`);
    lines.push("");
  }

  return lines.join("\n").trimEnd() + "\n";
}

export function toConvertSuccess(input: {
  videoId: string;
  title: string;
  channel: string | null;
  durationSeconds: number | null;
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  segments: TranscriptSegment[];
}): ConvertSuccess {
  const turns = groupSpeakerTurns(input.segments);
  return {
    videoId: input.videoId,
    title: input.title,
    channel: input.channel,
    durationSeconds: input.durationSeconds,
    languageCode: input.languageCode,
    languageName: captionLanguageLabel(
      input.languageName,
      input.isAutoGenerated,
    ),
    isAutoGenerated: input.isAutoGenerated,
    segmentCount: turns.length,
    markdown: buildMarkdown(input),
    filename: toSafeFilename(input.title),
    turns,
  };
}
