import type { TranscriptSegment, TranscriptTurn } from "./types";

export type { TranscriptTurn };

function splitOnSpeakerMarks(text: string): Array<{ change: boolean; text: string }> {
  const pieces = text.split(/>>+/);
  if (pieces.length === 1) {
    return [{ change: false, text: text.trim() }];
  }
  return pieces.map((piece, index) => ({
    change: index > 0,
    text: piece.replace(/\s+/g, " ").trim(),
  }));
}

export function groupSpeakerTurns(
  segments: TranscriptSegment[],
): TranscriptTurn[] {
  const turns: TranscriptTurn[] = [];
  let speaker: 0 | 1 = 0;

  for (const segment of segments) {
    const cues = splitOnSpeakerMarks(segment.text);
    for (const cue of cues) {
      if (cue.change) {
        speaker = speaker === 0 ? 1 : 0;
      }
      if (!cue.text) continue;

      const last = turns.at(-1);
      if (last && last.speaker === speaker) {
        last.text = `${last.text} ${cue.text}`.replace(/\s+/g, " ").trim();
      } else {
        turns.push({
          startMs: segment.startMs,
          speaker,
          text: cue.text,
        });
      }
    }
  }

  return turns;
}

export function captionLanguageLabel(
  languageName: string,
  isAutoGenerated: boolean,
): string {
  if (isAutoGenerated && !/auto-generated/i.test(languageName)) {
    return `${languageName} (auto-generated)`;
  }
  return languageName;
}
