import { toConvertSuccess } from "./markdown";
import { mintVideoPoToken } from "./potoken";
import type {
  CaptionTrack,
  ConvertError,
  ConvertSuccess,
  TranscriptSegment,
} from "./types";
import { canonicalWatchUrl } from "./youtube-url";

const BROWSER_UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

type PlayerResponse = {
  playabilityStatus?: { status?: string; reason?: string };
  videoDetails?: {
    videoId?: string;
    title?: string;
    author?: string;
    lengthSeconds?: string;
  };
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: Array<{
        baseUrl?: string;
        languageCode?: string;
        kind?: string;
        name?: { simpleText?: string; runs?: Array<{ text?: string }> };
      }>;
    };
  };
};

class ConvertFailure extends Error {
  constructor(
    readonly code: ConvertError["error"],
    message: string,
  ) {
    super(message);
    this.name = "ConvertFailure";
  }
}

function decodeEntities(text: string): string {
  return text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, " ")
    .replace(/&#x([0-9a-fA-F]+);/g, (_, hex: string) =>
      String.fromCharCode(parseInt(hex, 16)),
    )
    .replace(/&#(\d+);/g, (_, dec: string) =>
      String.fromCharCode(Number(dec)),
    )
    .replace(/\s+/g, " ")
    .trim();
}

function trackName(track: {
  name?: { simpleText?: string; runs?: Array<{ text?: string }> };
  languageCode?: string;
}): string {
  return (
    track.name?.simpleText ||
    track.name?.runs?.map((run) => run.text ?? "").join("") ||
    track.languageCode ||
    "unknown"
  );
}

function pickCaptionTrack(tracks: CaptionTrack[]): CaptionTrack | null {
  if (tracks.length === 0) return null;
  return tracks.find((track) => !track.isAutoGenerated) ?? tracks[0];
}

function extractJsonObject(source: string, marker: string): unknown | null {
  const idx = source.indexOf(marker);
  if (idx === -1) return null;
  const start = source.indexOf("{", idx + marker.length);
  if (start === -1) return null;

  let depth = 0;
  let quote: '"' | "'" | null = null;
  let escape = false;

  for (let i = start; i < source.length; i += 1) {
    const ch = source[i];
    if (quote) {
      if (escape) {
        escape = false;
        continue;
      }
      if (ch === "\\") {
        escape = true;
        continue;
      }
      if (ch === quote) quote = null;
      continue;
    }
    if (ch === '"' || ch === "'") {
      quote = ch;
      continue;
    }
    if (ch === "{") depth += 1;
    if (ch === "}") {
      depth -= 1;
      if (depth === 0) {
        try {
          return JSON.parse(source.slice(start, i + 1));
        } catch {
          return null;
        }
      }
    }
  }
  return null;
}

function captionTracksFromPlayer(player: PlayerResponse): CaptionTrack[] {
  const raw =
    player.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  return raw
    .filter((track): track is typeof track & { baseUrl: string } =>
      Boolean(track.baseUrl),
    )
    .map((track) => ({
      baseUrl: track.baseUrl.replace(/&amp;/g, "&"),
      languageCode: track.languageCode || "und",
      languageName: trackName(track),
      isAutoGenerated: track.kind === "asr",
    }));
}

async function fetchText(
  url: string,
  init?: RequestInit,
): Promise<{ ok: boolean; status: number; text: string }> {
  const response = await fetch(url, {
    ...init,
    headers: {
      "User-Agent": BROWSER_UA,
      "Accept-Language": "en-US,en;q=0.9,zh-TW;q=0.8",
      Accept:
        "text/html,application/xhtml+xml,application/xml,application/json,*/*;q=0.8",
      ...init?.headers,
    },
    signal: init?.signal ?? AbortSignal.timeout(20_000),
    cache: "no-store",
  });
  return {
    ok: response.ok,
    status: response.status,
    text: await response.text(),
  };
}

async function fetchOEmbed(videoId: string): Promise<{
  title: string | null;
  channel: string | null;
}> {
  const url = `https://www.youtube.com/oembed?url=${encodeURIComponent(canonicalWatchUrl(videoId))}&format=json`;
  try {
    const result = await fetchText(url, {
      headers: { Accept: "application/json" },
    });
    if (!result.ok) return { title: null, channel: null };
    const data = JSON.parse(result.text) as {
      title?: string;
      author_name?: string;
    };
    return {
      title: data.title ?? null,
      channel: data.author_name ?? null,
    };
  } catch {
    return { title: null, channel: null };
  }
}

function parseJson3(payload: string): TranscriptSegment[] {
  const data = JSON.parse(payload) as {
    events?: Array<{
      tStartMs?: number;
      dDurationMs?: number;
      segs?: Array<{ utf8?: string }>;
    }>;
  };
  const segments: TranscriptSegment[] = [];
  for (const event of data.events ?? []) {
    const text = decodeEntities(
      (event.segs ?? []).map((seg) => seg.utf8 ?? "").join(""),
    );
    if (!text || text === "\n") continue;
    segments.push({
      startMs: event.tStartMs ?? 0,
      durationMs: event.dDurationMs ?? 0,
      text,
    });
  }
  return segments;
}

async function fetchWatchPage(videoId: string): Promise<{
  html: string;
  player: PlayerResponse;
}> {
  const result = await fetchText(
    `${canonicalWatchUrl(videoId)}&hl=en&bpctr=9999999999&has_verified=1`,
    {
      headers: {
        Cookie: "CONSENT=YES+cb; SOCS=CAESEwgDEgk0ODE3Nzk3MjQaAmVuIAEaBgiA_LyaBg",
      },
    },
  );
  if (!result.ok) {
    throw new ConvertFailure(
      "YOUTUBE_BLOCKED",
      "Could not load the YouTube page. Try again, or use the local app / Chrome extension.",
    );
  }
  const player = extractJsonObject(
    result.text,
    "ytInitialPlayerResponse",
  ) as PlayerResponse | null;
  if (!player) {
    throw new ConvertFailure(
      "YOUTUBE_BLOCKED",
      "Could not parse the video data. YouTube may be blocking this IP.",
    );
  }
  return { html: result.text, player };
}

function visitorDataFromHtml(html: string): string {
  return html.match(/"visitorData":"([^"]+)"/)?.[1] ?? "";
}

async function fetchSegments(
  baseUrl: string,
  poToken: string,
): Promise<TranscriptSegment[]> {
  const jsonUrl = new URL(baseUrl);
  jsonUrl.searchParams.set("fmt", "json3");
  jsonUrl.searchParams.set("pot", poToken);
  jsonUrl.searchParams.set("c", "WEB");
  const result = await fetchText(jsonUrl.toString(), {
    headers: {
      Accept: "application/json,text/plain,*/*",
      Origin: "https://www.youtube.com",
    },
  });
  if (!result.ok || !result.text.trim()) {
    throw new ConvertFailure(
      "YOUTUBE_BLOCKED",
      "Caption data came back empty. YouTube may be blocking server requests — try locally or with the Chrome extension.",
    );
  }
  try {
    const segments = parseJson3(result.text);
    if (segments.length > 0) return segments;
  } catch {
    // fall through
  }
  throw new ConvertFailure(
    "NO_TRANSCRIPT",
    "A caption track was found, but the contents could not be parsed.",
  );
}

export async function convertVideo(videoId: string): Promise<ConvertSuccess> {
  const [{ html, player }, oembed] = await Promise.all([
    fetchWatchPage(videoId),
    fetchOEmbed(videoId),
  ]);

  const status = player.playabilityStatus?.status;
  if (status && status !== "OK" && status !== "LIVE_STREAM_OFFLINE") {
    throw new ConvertFailure(
      "VIDEO_UNAVAILABLE",
      player.playabilityStatus?.reason ||
        "This video is unavailable (it may be private, deleted, or region-locked).",
    );
  }

  const tracks = captionTracksFromPlayer(player);
  const track = pickCaptionTrack(tracks);
  if (!track) {
    throw new ConvertFailure(
      "NO_TRANSCRIPT",
      "This public video has no captions/CC, so it cannot be converted yet.",
    );
  }

  let poToken: string;
  try {
    poToken = await mintVideoPoToken(visitorDataFromHtml(html), videoId);
  } catch {
    throw new ConvertFailure(
      "YOUTUBE_BLOCKED",
      "Could not pass YouTube’s bot check. Local development usually works; Vercel datacenter IPs are sometimes blocked.",
    );
  }

  const segments = await fetchSegments(track.baseUrl, poToken);
  const durationValue = player.videoDetails?.lengthSeconds
    ? Number(player.videoDetails.lengthSeconds)
    : null;

  return toConvertSuccess({
    videoId,
    title: player.videoDetails?.title || oembed.title || `YouTube ${videoId}`,
    channel: player.videoDetails?.author || oembed.channel || null,
    durationSeconds: Number.isFinite(durationValue) ? durationValue : null,
    languageCode: track.languageCode,
    languageName: track.languageName,
    isAutoGenerated: track.isAutoGenerated,
    segments,
  });
}

export function toErrorPayload(error: unknown): {
  status: number;
  body: ConvertError;
} {
  if (error instanceof ConvertFailure) {
    const statusCode =
      error.code === "INVALID_URL"
        ? 400
        : error.code === "NO_TRANSCRIPT" || error.code === "VIDEO_UNAVAILABLE"
          ? 422
          : 502;
    return {
      status: statusCode,
      body: { error: error.code, message: error.message },
    };
  }

  return {
    status: 500,
    body: {
      error: "FETCH_FAILED",
      message: "An unexpected error occurred during conversion. Please try again.",
    },
  };
}
