export type CaptionTrack = {
  baseUrl: string;
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
};

export type TranscriptSegment = {
  startMs: number;
  durationMs: number;
  text: string;
};

export type TranscriptTurn = {
  startMs: number;
  speaker: 0 | 1;
  text: string;
};

export type ConvertSuccess = {
  videoId: string;
  title: string;
  channel: string | null;
  durationSeconds: number | null;
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  segmentCount: number;
  markdown: string;
  filename: string;
  turns: TranscriptTurn[];
};

export type ConvertErrorCode =
  | "INVALID_URL"
  | "VIDEO_UNAVAILABLE"
  | "NO_TRANSCRIPT"
  | "YOUTUBE_BLOCKED"
  | "FETCH_FAILED";

export type ConvertError = {
  error: ConvertErrorCode;
  message: string;
};
